apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qr-api
  template:
    metadata:
      labels:
        app: qr-api
    spec:
      containers:
      - name: qr-api
        image: pews/backend-api:latest