apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qr-frontend
  template:
    metadata:
      labels:
        app: qr-frontend
    spec:
      containers:
      - name: qr-frontend
        image: pews/frontend:latest
        ports:
        - containerPort: 3000
